ALTER TYPE "JobDocumentKind" ADD VALUE IF NOT EXISTS 'CERTIFICATION';
ALTER TYPE "JobDocumentKind" ADD VALUE IF NOT EXISTS 'EDUCATION';
ALTER TYPE "JobDocumentKind" ADD VALUE IF NOT EXISTS 'CAREER_OTHER';
