"use client";

import type { FC } from "react";
import {
    Activity,
    ActivityHeart,
    AlarmClock,
    Anchor,
    Award01,
    BankNote01,
    BatteryFull,
    Beaker02,
    Bell01,
    Bell02,
    BookOpen01,
    Bookmark,
    Briefcase01,
    Brush01,
    Building01,
    Building02,
    Bus,
    Calculator,
    Calendar,
    CalendarCheck01,
    CalendarHeart01,
    Camera01,
    Car01,
    CheckCircle,
    CheckDone01,
    CheckSquare,
    Clock,
    Cloud01,
    Code01,
    Coins01,
    Compass01,
    CreditCard01,
    CurrencyDollar,
    Database01,
    Drop,
    Droplets01,
    Edit01,
    Eye,
    FaceSmile,
    File02,
    Film01,
    Flag01,
    Flag02,
    Folder,
    Gift01,
    Globe01,
    GraduationHat01,
    Headphones01,
    Heart,
    HeartHand,
    Home01,
    Hourglass01,
    Key01,
    Laptop01,
    LayoutRight,
    Lightbulb02,
    List,
    Mail01,
    Map01,
    MarkerPin01,
    MedicalCross,
    MessageCircle01,
    Microphone01,
    Monitor01,
    Moon01,
    MoonStar,
    MusicNote01,
    Package,
    Palette,
    PenTool01,
    Pencil01,
    Phone,
    Phone01,
    PiggyBank01,
    Plane,
    Receipt,
    Rocket01,
    Scale01,
    Scissors01,
    Server01,
    Settings01,
    ShoppingCart01,
    Snowflake01,
    Star06,
    Sun,
    Sunrise,
    Tablet01,
    Tag01,
    Target04,
    ThumbsUp,
    Tool01,
    Train,
    Trash01,
    Trophy01,
    Truck01,
    Tv01,
    Umbrella01,
    Users01,
    Wallet02,
    Zap,
    ZapFast,
} from "@untitledui/icons";

/**
 * Shared, curated registry of life-OS icons used by the reusable icon-picker.
 *
 * Records store the component NAME string (e.g. "Scissors01") so the value can
 * safely cross the RSC boundary; this client-side map resolves it back to the
 * imported component. Every name here is verified to exist in
 * node_modules/@untitledui/icons/dist.
 */
export const ICON_REGISTRY: Record<string, FC<{ className?: string }>> = {
    // Errands / personal
    Scissors01,
    MedicalCross,
    ActivityHeart,
    Heart,
    Activity,
    Eye,
    Umbrella01,
    // Transport
    Car01,
    Bus,
    Train,
    Truck01,
    Plane,
    Anchor,
    // Home / places
    Home01,
    Building01,
    Building02,
    Key01,
    Tool01,
    Brush01,
    Trash01,
    MarkerPin01,
    Map01,
    Globe01,
    Compass01,
    // Shopping / gifts
    ShoppingCart01,
    Package,
    Gift01,
    Tag01,
    // People / comms
    Phone,
    Users01,
    Mail01,
    MessageCircle01,
    CalendarHeart01,
    // Media / hobbies
    Camera01,
    MusicNote01,
    Headphones01,
    Microphone01,
    Film01,
    Palette,
    // Learning / work
    BookOpen01,
    GraduationHat01,
    Lightbulb02,
    Briefcase01,
    PenTool01,
    Edit01,
    Folder,
    File02,
    // Tech
    Code01,
    Server01,
    Database01,
    Laptop01,
    Monitor01,
    Settings01,
    // Goals / status
    Award01,
    Trophy01,
    Star06,
    Target04,
    Flag01,
    Flag02,
    ThumbsUp,
    Bookmark,
    Zap,
    Rocket01,
    // Finance
    CreditCard01,
    BankNote01,
    Wallet02,
    Coins01,
    Receipt,
    Calculator,
    // Time / calendar / reminders
    Calendar,
    CalendarCheck01,
    Clock,
    AlarmClock,
    Hourglass01,
    Bell01,
    Bell02,
    // Lists / health misc
    CheckCircle,
    CheckSquare,
    CheckDone01,
    List,
    Beaker02,
    Droplets01,
    // Weather
    Sun,
    Moon01,
    Cloud01,
    Snowflake01,
    // Habits / fitness / wellness
    HeartHand,
    Drop,
    Scale01,
    Sunrise,
    MoonStar,
    FaceSmile,
    ZapFast,
    BatteryFull,
    Pencil01,
    Tablet01,
    Tv01,
    Phone01,
    PiggyBank01,
    CurrencyDollar,
    // Layout (panel toggle, etc.)
    LayoutRight,
};

/** Names offered in the picker, in a sensible display order. */
export const ICON_NAMES: string[] = Object.keys(ICON_REGISTRY);

/** Human-friendly search keywords per icon, used by the picker filter. */
export const ICON_KEYWORDS: Record<string, string> = {
    Scissors01: "haircut barber salon hair trim cut",
    MedicalCross: "dentist dental doctor physician medical clinic checkup health appointment",
    ActivityHeart: "medication pills pharmacy prescription health wellness vitals",
    Heart: "personal self-care love wellness favourite",
    Activity: "wellness fitness activity pulse exercise gym",
    Eye: "optometrist glasses eye exam vision contacts",
    Umbrella01: "insurance umbrella policy renewal rain",
    Car01: "car auto vehicle service dmv oil registration drive",
    Bus: "commute transit bus transport",
    Train: "train rail commute transit travel",
    Truck01: "delivery moving shipping truck",
    Plane: "travel flight trip vacation airport holiday",
    Anchor: "boat marina sailing dock harbour",
    Home01: "home house chores household",
    Building01: "office building company work apartment",
    Building02: "office rent apartment building work",
    Key01: "landlord keys lease rent property",
    Tool01: "repair fix handyman tools maintenance",
    Brush01: "cleaning paint painting brush decorate",
    Trash01: "garbage trash recycling waste bins collection",
    MarkerPin01: "appointment place location visit pin map",
    Map01: "map directions location route trip",
    Globe01: "world globe internet web international",
    Compass01: "compass direction explore navigate",
    ShoppingCart01: "groceries shopping store supermarket errands cart",
    Package: "packages parcel returns delivery shipping box",
    Gift01: "gift birthday present anniversary",
    Tag01: "tag label price sale category",
    Phone: "call phone ring contact",
    Users01: "catch up friends people meet hangout social team",
    Mail01: "email mail message inbox letter",
    MessageCircle01: "message chat text comment",
    CalendarHeart01: "anniversary date special occasion",
    Camera01: "photo camera pictures",
    MusicNote01: "music hobby lessons practice song",
    Headphones01: "headphones audio listen podcast music",
    Microphone01: "microphone record podcast voice sing",
    Film01: "film movie video cinema watch",
    Palette: "art paint colour design creative",
    BookOpen01: "read book study library learn",
    GraduationHat01: "school class course education study graduate",
    Lightbulb02: "idea project plan inspiration",
    Briefcase01: "work job errand business career",
    PenTool01: "design write draw pen vector",
    Edit01: "edit write note pencil",
    Folder: "folder files documents organise",
    File02: "file document paper page",
    Code01: "code dev programming software",
    Server01: "server backend hosting infrastructure",
    Database01: "database data storage db",
    Laptop01: "laptop computer work device",
    Monitor01: "monitor screen display desktop",
    Settings01: "settings config gear preferences",
    Award01: "goal achievement award milestone medal",
    Trophy01: "trophy win prize champion achievement",
    Star06: "priority favourite important star",
    Target04: "goal target aim focus objective",
    Flag01: "flag milestone goal mark",
    Flag02: "flag milestone goal mark",
    ThumbsUp: "like approve good thumbs up",
    Bookmark: "bookmark save read later",
    Zap: "energy fast power quick boost",
    Rocket01: "launch rocket startup goal fast",
    CreditCard01: "bill payment credit card pay due",
    BankNote01: "bank money cash banking",
    Wallet02: "wallet budget money spending",
    Coins01: "savings coins money invest",
    Receipt: "receipt expense reimburse",
    Calculator: "taxes accounting calculate finance",
    Calendar: "calendar date schedule event",
    CalendarCheck01: "calendar done scheduled confirmed event",
    Clock: "time clock schedule hour",
    AlarmClock: "alarm wake clock reminder time",
    Hourglass01: "time wait countdown hourglass",
    Bell01: "reminder alert generic notification",
    Bell02: "reminder alert notification",
    CheckCircle: "done complete check task tick",
    CheckSquare: "todo task checkbox done",
    CheckDone01: "todo task list done complete",
    List: "list todo tasks items",
    Beaker02: "lab science dose experiment chemistry",
    Droplets01: "water hydration drink drops",
    Sun: "sun day weather sunny morning",
    Moon01: "moon night sleep evening",
    Cloud01: "cloud weather sky",
    Snowflake01: "snow cold winter weather",
    HeartHand: "kindness gratitude care give meditate mindful self-care",
    Drop: "water hydrate drink hydration sip",
    Scale01: "weight scale weigh diet balance measure",
    Sunrise: "morning wake early sunrise routine rise dawn",
    MoonStar: "sleep night bedtime rest dream wind down",
    FaceSmile: "mood smile happy gratitude journal feeling positive",
    ZapFast: "energy fast quick power boost speed",
    BatteryFull: "energy battery recharge rest full power",
    Pencil01: "write journal note pencil draw diary",
    Tablet01: "tablet screen device doomscroll screen-time",
    Tv01: "tv television watch screen binge streaming",
    Phone01: "phone smartphone screen doomscroll social scroll mobile",
    PiggyBank01: "savings save money budget piggy spend no-spend",
    CurrencyDollar: "money dollar spending budget finance cash",
    LayoutRight: "panel sidebar layout right today",
};

/** Resolve a stored icon name to a component, falling back to Bell01. */
export function resolveIcon(name: string | null | undefined): FC<{ className?: string }> {
    if (name && ICON_REGISTRY[name]) return ICON_REGISTRY[name];
    return Bell01;
}
