// Coretex — default settings. Merged over the persisted settings.json on load.

import type { ColorScheme, CoretexConfig, KeyBinding } from "./schema.js";

export const DEFAULT_KEYBINDS: KeyBinding[] = [
    { actionId: "clear-buffer", chords: ["Ctrl+Shift+K"], enabled: true },
    { actionId: "close-pane", chords: ["Ctrl+Shift+W"], enabled: true },
    { actionId: "copy", chords: ["Ctrl+Shift+C", "Ctrl+Insert"], enabled: true },
    { actionId: "paste", chords: ["Ctrl+Shift+V", "Shift+Insert"], enabled: true },
    { actionId: "select-all", chords: ["Ctrl+Shift+A"], enabled: true },
    { actionId: "find", chords: ["Ctrl+Shift+F"], enabled: true },
    { actionId: "font-size-increase", chords: ["Ctrl+=", "Ctrl+Plus"], enabled: true },
    { actionId: "font-size-decrease", chords: ["Ctrl+-", "Ctrl+Minus"], enabled: true },
    { actionId: "new-tab", chords: ["Ctrl+Shift+T"], enabled: true },
    { actionId: "duplicate-tab", chords: ["Ctrl+Shift+D"], enabled: true },
    { actionId: "duplicate-pane", chords: ["Alt+Shift+D"], enabled: true },
    { actionId: "split-down", chords: ["Alt+Shift+-"], enabled: true },
    { actionId: "split-right", chords: ["Alt+Shift+=", "Alt+Shift+Plus"], enabled: true },
    { actionId: "next-tab", chords: ["Ctrl+Tab"], enabled: true },
    { actionId: "previous-tab", chords: ["Ctrl+Shift+Tab"], enabled: true },
    { actionId: "move-focus-left", chords: ["Alt+ArrowLeft"], enabled: true },
    { actionId: "move-focus-right", chords: ["Alt+ArrowRight"], enabled: true },
    { actionId: "move-focus-up", chords: ["Alt+ArrowUp"], enabled: true },
    { actionId: "move-focus-down", chords: ["Alt+ArrowDown"], enabled: true },
    { actionId: "scroll-up", chords: ["Ctrl+Shift+ArrowUp"], enabled: true },
    { actionId: "scroll-down", chords: ["Ctrl+Shift+ArrowDown"], enabled: true },
    { actionId: "command-palette", chords: ["Ctrl+Shift+P"], enabled: true },
    { actionId: "open-settings", chords: ["Ctrl+,"], enabled: true },
    { actionId: "toggle-fullscreen", chords: ["Alt+Enter", "F11"], enabled: true },
    { actionId: "reopen-closed-tab", chords: ["Ctrl+Shift+Y"], enabled: true },
    { actionId: "ai-command-bar", chords: ["Ctrl+K"], enabled: true },
    { actionId: "open-ai-pane", chords: ["Ctrl+Alt+A"], enabled: true },
    { actionId: "open-browser-pane", chords: ["Ctrl+Shift+B"], enabled: true },
    { actionId: "open-file-manager", chords: ["Ctrl+Shift+E"], enabled: true },
    { actionId: "quick-ssh-connect", chords: ["Ctrl+Alt+S"], enabled: true },
    { actionId: "global-node-search", chords: ["Ctrl+Shift+Space"], enabled: true },
    ...Array.from({ length: 9 }, (_, i): KeyBinding => ({ actionId: `switch-tab-${i + 1}`, chords: [`Ctrl+Alt+${i + 1}`], enabled: true })),
    ...Array.from({ length: 9 }, (_, i): KeyBinding => ({ actionId: `new-tab-profile-${i + 1}`, chords: [`Ctrl+Shift+${i + 1}`], enabled: true })),
];

function scheme(name: string, c: Omit<ColorScheme, "name" | "builtIn">): ColorScheme {
    return { name, builtIn: true, ...c };
}

export const BUILTIN_SCHEMES: ColorScheme[] = [
    scheme("Campbell", {
        background: "#0C0C0C", foreground: "#CCCCCC", cursor: "#FFFFFF", cursorAccent: "#0C0C0C",
        selectionBackground: "#FFFFFF", selectionForeground: "#0C0C0C",
        black: "#0C0C0C", red: "#C50F1F", green: "#13A10E", yellow: "#C19C00", blue: "#0037DA", purple: "#881798", cyan: "#3A96DD", white: "#CCCCCC",
        brightBlack: "#767676", brightRed: "#E74856", brightGreen: "#16C60C", brightYellow: "#F9F1A5", brightBlue: "#3B78FF", brightPurple: "#B4009E", brightCyan: "#61D6D6", brightWhite: "#F2F2F2",
    }),
    scheme("Campbell Powershell", {
        background: "#012456", foreground: "#CCCCCC", cursor: "#FFFFFF", cursorAccent: "#012456",
        selectionBackground: "#FFFFFF", selectionForeground: "#012456",
        black: "#0C0C0C", red: "#C50F1F", green: "#13A10E", yellow: "#C19C00", blue: "#0037DA", purple: "#881798", cyan: "#3A96DD", white: "#CCCCCC",
        brightBlack: "#767676", brightRed: "#E74856", brightGreen: "#16C60C", brightYellow: "#F9F1A5", brightBlue: "#3B78FF", brightPurple: "#B4009E", brightCyan: "#61D6D6", brightWhite: "#F2F2F2",
    }),
    scheme("Dracula", {
        background: "#282A36", foreground: "#F8F8F2", cursor: "#F8F8F2", cursorAccent: "#282A36",
        selectionBackground: "#44475A", selectionForeground: "#F8F8F2",
        black: "#21222C", red: "#FF5555", green: "#50FA7B", yellow: "#F1FA8C", blue: "#BD93F9", purple: "#FF79C6", cyan: "#8BE9FD", white: "#F8F8F2",
        brightBlack: "#6272A4", brightRed: "#FF6E6E", brightGreen: "#69FF94", brightYellow: "#FFFFA5", brightBlue: "#D6ACFF", brightPurple: "#FF92DF", brightCyan: "#A4FFFF", brightWhite: "#FFFFFF",
    }),
    scheme("Solarized Dark", {
        background: "#002B36", foreground: "#839496", cursor: "#839496", cursorAccent: "#002B36",
        selectionBackground: "#073642", selectionForeground: "#93A1A1",
        black: "#073642", red: "#DC322F", green: "#859900", yellow: "#B58900", blue: "#268BD2", purple: "#D33682", cyan: "#2AA198", white: "#EEE8D5",
        brightBlack: "#002B36", brightRed: "#CB4B16", brightGreen: "#586E75", brightYellow: "#657B83", brightBlue: "#839496", brightPurple: "#6C71C4", brightCyan: "#93A1A1", brightWhite: "#FDF6E3",
    }),
    scheme("Solarized Light", {
        background: "#FDF6E3", foreground: "#657B83", cursor: "#657B83", cursorAccent: "#FDF6E3",
        selectionBackground: "#EEE8D5", selectionForeground: "#586E75",
        black: "#073642", red: "#DC322F", green: "#859900", yellow: "#B58900", blue: "#268BD2", purple: "#D33682", cyan: "#2AA198", white: "#EEE8D5",
        brightBlack: "#002B36", brightRed: "#CB4B16", brightGreen: "#586E75", brightYellow: "#657B83", brightBlue: "#839496", brightPurple: "#6C71C4", brightCyan: "#93A1A1", brightWhite: "#FDF6E3",
    }),
    scheme("Tokyo Night", {
        background: "#1A1B26", foreground: "#A9B1D6", cursor: "#C0CAF5", cursorAccent: "#1A1B26",
        selectionBackground: "#33467C", selectionForeground: "#C0CAF5",
        black: "#15161E", red: "#F7768E", green: "#9ECE6A", yellow: "#E0AF68", blue: "#7AA2F7", purple: "#BB9AF7", cyan: "#7DCFFF", white: "#A9B1D6",
        brightBlack: "#414868", brightRed: "#F7768E", brightGreen: "#9ECE6A", brightYellow: "#E0AF68", brightBlue: "#7AA2F7", brightPurple: "#BB9AF7", brightCyan: "#7DCFFF", brightWhite: "#C0CAF5",
    }),
    scheme("Nord", {
        background: "#2E3440", foreground: "#D8DEE9", cursor: "#D8DEE9", cursorAccent: "#2E3440",
        selectionBackground: "#434C5E", selectionForeground: "#D8DEE9",
        black: "#3B4252", red: "#BF616A", green: "#A3BE8C", yellow: "#EBCB8B", blue: "#81A1C1", purple: "#B48EAD", cyan: "#88C0D0", white: "#E5E9F0",
        brightBlack: "#4C566A", brightRed: "#BF616A", brightGreen: "#A3BE8C", brightYellow: "#EBCB8B", brightBlue: "#81A1C1", brightPurple: "#B48EAD", brightCyan: "#8FBCBB", brightWhite: "#ECEFF4",
    }),
    scheme("Gruvbox Dark", {
        background: "#282828", foreground: "#EBDBB2", cursor: "#EBDBB2", cursorAccent: "#282828",
        selectionBackground: "#504945", selectionForeground: "#EBDBB2",
        black: "#282828", red: "#CC241D", green: "#98971A", yellow: "#D79921", blue: "#458588", purple: "#B16286", cyan: "#689D6A", white: "#A89984",
        brightBlack: "#928374", brightRed: "#FB4934", brightGreen: "#B8BB26", brightYellow: "#FABD2F", brightBlue: "#83A598", brightPurple: "#D3869B", brightCyan: "#8EC07C", brightWhite: "#EBDBB2",
    }),
    scheme("One Half Dark", {
        background: "#282C34", foreground: "#DCDFE4", cursor: "#A3B3CC", cursorAccent: "#282C34",
        selectionBackground: "#474E5D", selectionForeground: "#DCDFE4",
        black: "#282C34", red: "#E06C75", green: "#98C379", yellow: "#E5C07B", blue: "#61AFEF", purple: "#C678DD", cyan: "#56B6C2", white: "#DCDFE4",
        brightBlack: "#5A6374", brightRed: "#E06C75", brightGreen: "#98C379", brightYellow: "#E5C07B", brightBlue: "#61AFEF", brightPurple: "#C678DD", brightCyan: "#56B6C2", brightWhite: "#DCDFE4",
    }),
    scheme("Coretex Dark", {
        background: "#0A0C10", foreground: "#F5F6F8", cursor: "#C3A6FF", cursorAccent: "#0A0C10",
        selectionBackground: "#1C1530", selectionForeground: "#F5F6F8",
        black: "#14171D", red: "#F04438", green: "#17B26A", yellow: "#F79009", blue: "#7AA2F7", purple: "#7F56D9", cyan: "#22CCEE", white: "#9BA0A8",
        brightBlack: "#646A73", brightRed: "#FF6B5E", brightGreen: "#47CD89", brightYellow: "#FDB022", brightBlue: "#A6C0FF", brightPurple: "#C3A6FF", brightCyan: "#67E3F9", brightWhite: "#F5F6F8",
    }),
    scheme("Coretex Hacker", {
        background: "#020403", foreground: "#17B26A", cursor: "#17B26A", cursorAccent: "#020403",
        selectionBackground: "#06351F", selectionForeground: "#47CD89",
        black: "#020403", red: "#F04438", green: "#17B26A", yellow: "#F79009", blue: "#0BA5EC", purple: "#7F56D9", cyan: "#22CCEE", white: "#85E0A3",
        brightBlack: "#0A3D26", brightRed: "#FF6B5E", brightGreen: "#47CD89", brightYellow: "#FDB022", brightBlue: "#36BFFA", brightPurple: "#C3A6FF", brightCyan: "#67E3F9", brightWhite: "#D3F8DF",
    }),
];

export const DEFAULT_CONFIG: CoretexConfig = {
    account: { connected: false, sync: { settings: true, themes: true, profiles: true, sshConnections: true } },
    startup: {
        defaultProfileId: "profile-default",
        defaultTerminalApp: false,
        language: "system",
        imeMode: "alphanumeric",
        launchOnLogin: false,
        onStart: "new-tab",
        newInstance: "window",
        launchCols: 120,
        launchRows: 30,
        launchArgs: "",
    },
    session: { restore: true, workspacePresetId: null },
    interaction: {
        clipboard: {
            autoCopySelection: false,
            copyFormats: "plain",
            trimBlockSelection: true,
            trimOnPaste: true,
            wordDelimiters: "/\\()\"'-,.;<>~!@#$%^&",
        },
        windowPanes: {
            snapToGrid: true,
            tabSwitcherStyle: "strip",
            focusFollowsMouse: false,
            ctrlScrollFontSize: true,
            ctrlShiftScrollOpacity: true,
        },
        linksSelection: { detectUrls: true, searchUrlTemplate: "https://www.bing.com/search?q=%s", colorSelectedText: false },
        ai: { assistOnError: true, commandBar: true, smartPasteGuard: true },
    },
    appearance: {
        application: { theme: "dark", newTabPosition: "end", activeColorScheme: "Campbell", accent: "#ef4242" },
        tabs: { alwaysShow: true, showInFullScreen: false, acrylic: false, widthMode: "equal", titleFromActiveTerminal: true },
        window: {
            hideTitleBar: false,
            alwaysOnTop: false,
            paneAnimations: true,
            autoHideOnBlur: false,
            adminShield: true,
            acrylicWhenUnfocused: false,
        },
        tray: { alwaysShowIcon: true, minimizeToTray: false },
        coretex: { sidebarWidth: 256, sidebarCollapse: "expanded", sidebarDensity: "comfortable", sidebarShowProjects: true, statusBar: true, windowOpacity: 100, blurRadius: 0 },
        locale: { dateFormat: "YYYY-MM-DD", timeFormat: "24h", units: "metric", currency: "USD" },
        badges: {
            // Priority: a coordinated cool -> hot scale.
            priority: { low: "gray", medium: "blue", high: "warning", critical: "error" },
            // Role: a distinct hue per role.
            role: {
                orchestrator: "purple",
                planner: "brand",
                researcher: "blue",
                developer: "indigo",
                reviewer: "orange",
                writer: "pink",
                analyst: "sky",
                devops: "warning",
                qa: "success",
                custom: "gray",
            },
        },
    },
    rendering: {
        render: {
            graphicsApi: "auto",
            disablePartialSwapchain: false,
            softwareRendering: false,
            webglTerminals: true,
            fontLigatures: true,
            antialiasing: "grayscale",
        },
        compat: { runInBackground: true, textMeasurement: "grapheme" },
    },
    keybinds: DEFAULT_KEYBINDS,
    profiles: [
        {
            id: "profile-default",
            name: "Default",
            commandLine: "",
            args: "",
            cwd: "",
            elevated: false,
            icon: "terminal",
            tabColor: null,
            appearance: {
                colorScheme: "Default",
                fontFace: "JetBrains Mono",
                fontSize: 14,
                fontWeight: "normal",
                ligatures: true,
                cursorShape: "bar",
                cursorBlink: true,
                bgOpacity: 100,
                padding: "8",
            },
        },
    ],
    colorSchemes: BUILTIN_SCHEMES,
    aiProviders: [
        { provider: "ollama", enabled: true, baseUrl: "http://localhost:11434", keyConfigured: false, defaultModel: "llama3.1:latest" },
        { provider: "lmstudio", enabled: true, baseUrl: "http://localhost:1234", keyConfigured: false },
        { provider: "anthropic", enabled: false, keyConfigured: false, defaultModel: "claude-sonnet-4-5", authMode: "claude-plan" },
        { provider: "openai", enabled: false, keyConfigured: false, defaultModel: "gpt-4o-mini" },
        { provider: "gemini", enabled: false, keyConfigured: false },
        { provider: "openrouter", enabled: false, keyConfigured: false, baseUrl: "https://openrouter.ai/api", defaultModel: "anthropic/claude-sonnet-4" },
        { provider: "openclaw", enabled: false, keyConfigured: false, baseUrl: "http://127.0.0.1:18789", defaultModel: "" },
    ],
    agents: [],
    codingAgents: [
        { id: "claude", name: "Claude Code", provider: "anthropic", enabled: true, logoDomain: "anthropic.com" },
        { id: "codex", name: "Codex", provider: "openai", enabled: true, logoDomain: "openai.com" },
        { id: "opencode", name: "OpenCode", provider: "ollama", enabled: false, logoDomain: "opencode.ai" },
        { id: "ollama", name: "Ollama", provider: "ollama", enabled: true, logoDomain: "ollama.com" },
        { id: "lmstudio", name: "LM Studio", provider: "lmstudio", enabled: false, logoDomain: "lmstudio.ai" },
        { id: "openai", name: "OpenAI", provider: "openai", enabled: false, logoDomain: "openai.com" },
        { id: "gemini", name: "Gemini", provider: "gemini", enabled: false, logoDomain: "gemini.google.com" },
        { id: "openclaw", name: "OpenClaw", provider: "openclaw", enabled: false, logoDomain: "openclaw.ai" },
        { id: "openrouter", name: "OpenRouter", provider: "openrouter", enabled: false, logoDomain: "openrouter.ai" },
    ],
    mcpServers: [],
    mcpBuiltIns: [
        { id: "coretex-browser", description: "Fetch and read web pages", caps: ["tools"], enabled: false },
        { id: "coretex-filesystem", description: "Read and write files in the Coretex virtual filesystem", caps: ["resources", "tools"], enabled: true },
        { id: "coretex-git", description: "Git status, log, diff and commit", caps: ["tools"], enabled: false },
        { id: "coretex-ssh", description: "Run commands on connected remote hosts", caps: ["tools"], enabled: false },
        { id: "coretex-terminal", description: "Let AI execute shell commands subject to the Security terminal policy", caps: ["tools"], enabled: true },
    ],
    database: { connections: [], defaultStore: "~/.coretex" },
    docker: {
        enabled: true,
        socketPath: "",
        host: "",
        tlsVerify: false,
        autoRefresh: true,
        pollIntervalSec: 6,
        showStoppedContainers: true,
        confirmDestructive: true,
        pruneDefaults: {
            containers: true,
            images: true,
            volumes: true,
            networks: true,
            buildCache: true,
        },
        registries: [],
    },
    dockerLinks: {},
    databaseLinks: {},
    remote: { sshHosts: [], mesh: { enabled: false, pairedDevices: [], pairingInvite: null }, integrations: [] },
    security: {
        autonomousTerminal: "approval",
        denylist: ["rm -rf /", "rm -rf ~", ":(){ :|:& };:", "mkfs", "dd if=", "> /dev/sda"],
        allowlist: [],
        maxCommandLength: 8192,
        telemetry: false,
        crashReports: false,
        redactSecrets: true,
        dailyCostLimitUSD: 5,
    },
    ai: { enabled: true },
    extensions: [],
    profile: { fullName: "", nickname: "", email: "", about: "", pronouns: "", avatarUrl: "" },
    memory: { enabled: true, autoGenerate: false, referencePastChats: true },
    toolAccess: {
        mode: "ask",
        tools: { filesystem: true, terminal: true, web: true, browser: false, codeExec: false, database: true },
    },
    notifications: {
        categories: {
            taskDone: true,
            approvalNeeded: true,
            agentError: true,
            budget: true,
            serverDown: false,
            taskStarted: false,
            agentIdle: false,
            agentPaused: true,
            mentionInChat: true,
            emailSorted: false,
            scheduleReminder: true,
            deployFinished: true,
            mcpError: true,
            updateAvailable: true,
            fileWatch: false,
            chatReply: true,
        },
        sound: false,
        backgroundOnly: false,
        desktopEnabled: true,
        quietHours: { enabled: false, start: "22:00", end: "07:00" },
        digest: { enabled: false, everyMinutes: 30 },
        mobile: {
            enabled: false,
            categories: {
                taskDone: true,
                approvalNeeded: true,
                agentError: true,
                budget: true,
                serverDown: false,
                taskStarted: false,
                agentIdle: false,
                agentPaused: true,
                mentionInChat: true,
                emailSorted: false,
                scheduleReminder: true,
                deployFinished: true,
                mcpError: true,
                updateAvailable: false,
                fileWatch: false,
                chatReply: true,
            },
            agentControls: true,
            approveFromMobile: true,
            startAgents: false,
            pauseResumeAgents: true,
            haltAgents: true,
            viewAgentStatus: true,
            criticalOnly: false,
            vibrate: true,
            showPreview: true,
            badgeCount: true,
        },
    },
    agentRuntime: {
        claudeAuth: "anthropic-api",
        useClaudeSdkForClaude: true,
        useCodexCliForOpenAI: true,
        useGeminiCliForGemini: true,
        defaultNonClaudeRuntime: "universal",
    },
    composer: {
        defaultAwareness: true,
        allowAutoBypass: false,
        conversationScope: {},
    },
    terminalBuddy: {
        enabled: true,
        defaultModel: "",
        defaultProvider: "",
        defaultMode: "suggest",
        maxRetries: 3,
        webSearch: false,
        alwaysConfirmDestructive: true,
        probeOnStart: true,
        buddyBarPosition: "bottom",
        perTerminal: {},
    },
    autocomplete: {
        enabled: true,
        ghostText: true,
        dropdown: true,
        providers: {
            history: true,
            path: true,
            specs: true,
            pathExecutables: true,
            ai: false,
        },
        nativeTabFallback: "when-no-suggestion",
        debounceMs: 120,
    },
    speech: {
        enabled: true,
        language: "",
        pushToTalk: false,
        autoSpace: true,
        showInAskAi: true,
        showInCommandBar: true,
        showInTerminalBuddy: true,
        showInProjectChat: true,
        injectIntoTerminal: false,
    },
    filesView: {
        defaultView: "columns",
        density: "comfortable",
        showHidden: false,
        sortBy: "name",
        sortDir: "asc",
        confirmDelete: true,
        gridSize: 96,
        showGitStatus: true,
        showSizeColumn: true,
        showModifiedColumn: true,
        showTypeColumn: true,
        openOn: "single-click",
        enableQuickLook: true,
        defaultSearchScope: "folder",
        sidebarWidth: 208,
        listingWidthWhenEditorOpen: 340,
        editorWordWrap: false,
        editorFontSize: 13,
        editorMinimap: false,
        hideSystemFolders: true,
        hidePatterns: "",
    },
};
